### ISSUE TITLE
Changing Feed Template don't show up in the Widget Manager

### ISSUE THREAD

**Issue by JokerGermany** [element-hq/element-integration-manager#100]
**Describe the bug**
I like the new Option changing the template and it generates an Event.
e.g.
`{
    "content": {
        "label": "Home Assistant Core Release",
        "template": "$FEEDNAME: $LINK",
        "url": "https://github.com/home-assistant/core/releases.atom"
    },
    "origin_server_ts": 1686348016072,
    "sender": "@feeds:integrations.ems.host",
    "state_key": "https://github.com/home-assistant/core/releases.atom",
    "type": "uk.half-shot.matrix-hookshot.feed",
    "unsigned": {
        "replaces_state": "$zNFyx4v_DzRi-ltrfvW2A-GlQ2GGjPgt9uyOV6SaTI0",
        "prev_content": {
            "label": "Home Assistant Core Release",
            "template": " $FEEDNAME: $LINK",
            "url": "https://github.com/home-assistant/core/releases.atom"
        },
        "prev_sender": "@feeds:integrations.ems.host"
    },
    "event_id": "$ZejVAmaOTZDOgz81K9qrloHrCvSXGB6A4Mxdv7O-xng",
    "room_id": "!ApTSFhfEdqtycWkvse:matrix.org"
}`
But it doesn't show up in the Widgfet Manager
![grafik](https://github.com/vector-im/element-integration-manager/assets/30293477/fc4e671d-331a-404b-be71-112d61e26ecf)

**To Reproduce**
Change the Template

**Expected behavior**
Showing the new Template

**Client (please complete the following information):**
Version von Element Desktop: 1.11.31
Version von Olm: 3.2.14

**Additional context**
Perhaps changing the template causes #99 :thinking:

**Comment by Half-Shot** [comment]
@JokerGermany So I understand this, you are:

- Editing the template inside the widget and hitting save?
- And the template doesn't persist in the widget after changing it?

**Comment by JokerGermany** [comment]
> @JokerGermany So I understand this, you are:
> 
>     * Editing the template inside the widget and hitting save?
> 
>     * And the template doesn't persist in the widget after changing it?

yes

**Comment by Twi1ightSparkle** [comment]
Following up on this, saving the template from the widget updates the state event, but the widget doesn't read the template from the event when opening the feed

**Comment by Half-Shot** [comment]
In the future these need to be upstreamed to https://github.com/matrix-org/matrix-hookshot/issues so I remember to read them. My fault.
