### ISSUE TITLE
EtherPad widget says You do not have permission to access this pad

### ISSUE THREAD

**Issue by vranki** [element-hq/element-integration-manager#124]
**Describe the bug**
Etherpad widged doesn't allow me to see my pad added to a Matrix room.

**To Reproduce**
1. Add etherpad widget to a room (unencrypted in this case)
2. Use it fine for some time
3. One day it says "You do not have permission to access this pad" and doesn't show the content (which is presumably lost now)

**Expected behavior**
Working etherpad

**Screenshots**

![image](https://github.com/element-hq/element-integration-manager/assets/81116/e67b7abe-82f6-435d-aade-a2aed7c7bdbb)

**Client (please complete the following information):**
 - Matrix Client and Version: Element (web/desktop)
 - Matrix Client Version: up to date
 - Browser Firefox
 - Browser Version 127

**Comment by kaffeeknecht** [comment]
Same here.
Might be related to recent updates to Element-Web 1.11.69 and/or Synapse 1.109.0

EDIT: Downgrade to element-web 1.11.68  didn't solve the Problem

**Comment by CsatiZoltan** [comment]
Same here, see #125

**Comment by cbs228** [comment]
Same here, but mine stopped working on Monday, 1 July. I have a direct URL for the pad that I used just fine in my browser on 24 June, but now that doesn't work either.

**Comment by CsatiZoltan** [comment]
@cbs228 Public Etherpad instances, such as https://etherpad.wikimedia.org/, seem to work fine.

**Comment by cbs228** [comment]
@CsatiZoltan, yes, but I would like my scalar.vector.im instance document to be restored if at all possible. My most recent backup of this file was from several months ago.

**Comment by CsatiZoltan** [comment]
@cbs228 Same here, I lost some precious notes.

**Comment by CsatiZoltan** [comment]
Now the notes load again. For you, @cbs228 , @kaffeeknecht , @vranki ?

**Comment by vranki** [comment]
Seems to work now, no data lost.

**Comment by kaffeeknecht** [comment]
Looks good now. =)
