### ISSUE TITLE
Jitsi widget doesn't work in China

### ISSUE THREAD

**Issue by XJY00** [element-hq/element-integration-manager#126]
### Steps to reproduce

I can not connect to voice call and video call in private chat room, indicating connection error
I can't share my screen after joining a video conference in a public room

#### What did you expect?
I want to talk normally in the private room and share the screen in the public room
I initially think that the reason for the error is that my server is in China, and the link address of the new version of the video plug-in service cannot be connected in China. I hope you can provide the compatibility option of the old version for servers in special regions
#### What happened instead?
I'm using the desktop client on my home server deployment, using Synapse
The voice call and video call in the private chat room cannot be connected, indicating a connection error
Screen sharing is not possible after joining a video conference in a public room

### Operating system

Windows11

### Application version

Element 版本： 1.11.70 Crypto version: Rust SDK 0.7.1 (80a151e), Vodozemac 0.6.0

### How did you install the app?

https://element.io/download

### Homeserver

Synapse

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs from you

**Comment by t3chguy** [comment]
> Screen sharing is not possible after joining a video conference in a public room

That's https://github.com/element-hq/element-web/issues/32398

**Comment by t3chguy** [comment]
The issue here is meet.element.io is not accessible via the Great Firewall of China
