### ISSUE TITLE
`Failed to make link: Timed out` when trying to setup Slack integration

### ISSUE THREAD

**Issue by astrojuanlu** [element-hq/element-integration-manager#3]
### Description

I am trying to setup Slack integration with my Matrix channel, but it times out every time.

### Steps to reproduce

1. Login with Slack in the integration modal
2. Click "List channels" and pick the desired one
3. Wait, and see `Failed to make link: Timed out` error
4. (Just in case) Verify that the integration is indeed not working

Logs being sent: yes/no

![Screenshot_2021-05-12 Element  12  readthedocs sphinx-rtd-theme](https://user-images.githubusercontent.com/316517/117969071-3e954b00-b327-11eb-9ee0-42c43af29fa5.png)

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Firefox 88.0.1
- **OS**: Linux Mint 20.1 Cinnamon
- **URL**: https://staging.element.io/#/room/#readthedocs_sphinx-rtd-theme:gitter.im

**Comment by Half-Shot** [comment]
I'm not actively looking at this at the moment. Any logging we would have had for the above failures won't be available now. If folks are still experiencing this, can they reply with their mxid and the team can investigate.

**Comment by astrojuanlu** [comment]
I cannot test this anymore, unsure if it's still happening.

**Comment by valerio-bozzolan** [comment]
It's still happening for me while trying to connect the `#glamhack:matrix.org` to this Slack chat https://app.slack.com/client/T0486GEPK51/C0483L67GJ1

I'm able to list the Channels, but I get the timeout when I select the specific channel from Element.

**Comment by lrusak** [comment]
Yes it's still happening to me. I'm really not sure what the problem is. Who can help debug this?
