### ISSUE TITLE
`@appservice:libera.chat` remains as matrix room admin afer IRC channel bridging is unlinked.

### ISSUE THREAD

**Issue by tim-seoss** [element-hq/element-integration-manager#41]
**Describe the bug**
After removing a bridged IRC channel from a Matrix room (libera.chat), `@appservice:libera.chat` remains an administrator in the Matrix room

**To Reproduce**

1. In Element desktop, go to 'Add widget, bridges and bots' in the room side panel.
2. Choose 'IRC bridge' and connect to a libera.chat channel.
3. In Element desktop, go to 'Add widget, bridges and bots' in the room side panel.
4. Remove the IRC bridge
5. In Element desktop, go to room settings -> 'Roles and Permissions', `@appservice:libera.chat` remains in the list of room administrators.

**Expected behaviour**

In step 5 above, `@appservice:libera.chat` would no longer be listed as a room admin.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Element version: 1.11.24, Olm version: 3.2.12

**Comment by Half-Shot** [comment]
I believe the user is now gone from every room.
