### ISSUE TITLE
[Feeds] Adding bot and migration not working properly

### ISSUE THREAD

**Issue by natrius** [element-hq/element-integration-manager#45]
**Describe the bug**
I'm admin in some rooms and when trying to migrate according to https://ems-docs.element.io/books/element-cloud-documentation/page/migrate-to-the-new-github-and-feeds-bots i klick on feeds and on "Add" then the only thing thats happening is, the Mod gets promoted `natrius changed the power level of @feeds:integrations.ems.host from Default to Moderator.` and i get a message `Something went wrong. Failed to add this extension to the room: You need to be able to invite users to do that.` (I'm admin...) and i'm stuck there-

At random i am able to get further and the bot gets invited (just able to it in one room, the second room i'm trying to migrate its stuck) and it times out and after that i was not able to see a "migrate" button or anything and i have to search what i used to set up that bot. 

**Expected behavior**
Well, not timing out all the time so i can try it :)

**Screenshots**
First click on "Add"
![grafik](https://user-images.githubusercontent.com/7243447/227048239-97b5f1fa-def4-4f97-bdea-a063e28a95fc.png)
After that in the chat (why mod? O.o)
![grafik](https://user-images.githubusercontent.com/7243447/227048300-027caf47-fd1e-464a-a97a-a4f2dc4b0de2.png)
And repeat. 

**Desktop (please complete the following information):**
 - OS: Windows 10
- Element version: 1.11.25
- Olm version: 3.2.12

**Comment by natrius** [comment]
By sheer luck i managed to get further in another room but immediately stuck with another message
![grafik](https://user-images.githubusercontent.com/7243447/227048920-c123ec18-f4f5-48ae-9c0c-b64805f39a50.png)

Afterwards i was able to migrate in that room.  After that i got back to the room i mentioned in the first posting and it worked there as well. So it needs some minutes between each step, some retrying and then it might work.

**Comment by MarkWieczorek** [comment]
Same problem. This works for some rooms, but not for most. With dozens of rooms to update, the migration is highly non-optimal.

**Comment by natrius** [comment]
Thanks for the answer! 
Sounds correct, to add: Point1 it seems like it does not join at all after the initial fail (no permission). It may be that point 2 leads to point 1 as well.

**Comment by razzeee** [comment]
My bot seems to have joined and has been elevated, but I only get this message, which isn't helpful

![image](https://user-images.githubusercontent.com/5943908/227470270-e398b17d-2ce8-4460-8b04-aa676e230749.png)

**Comment by Half-Shot** [comment]
@razzeee Can you give me a RoomID that you tried to bridge, I'll track down the error.

**Comment by razzeee** [comment]
@Half-Shot 
!zDwUBYVNEXEzSbTYwI:matrix.org

**Comment by natrius** [comment]
Take your time. After the intial "no permissions" wait a bit and try it occasionally again. Then you will see the bot "feed" joining, its probbaly not working on the spot as well, again, come back a bit later and simply try again. Annoying, but it works.

**Comment by MarkWieczorek** [comment]
For me, I have two admins in the room. One successfully added the new bot, bot the pre-existing subscription isn't listed. When the other admin tries to open the bot integration, they get the error "error Failed to fetch existing connections: User is not joined to the room."

room id: !leKewkNLGCqpFqcBds:matrix.org

**Comment by Half-Shot** [comment]
We're still looking into it, broadly it looks like the (federated) user @feeds:integrations.ems.host is failing to join some rooms. We've been quietly working on it, and in most cases I have found it will join after a few attempts. Using the `/rageshake` command in Element is helpful for us to track it down, because it gives us useful logs. Please link to this issue when doing so if you can.

Unfortunately while we can reproduce the intermittent failure, the continuous failures could be a few things. Again, unfortunately mass testing is the only way you'll find some of these bugs.

**Comment by Half-Shot** [comment]
We're still looking into it, broadly it looks like the (federated) user @feeds:integrations.ems.host is failing to join some rooms. We've been quietly working on it, and in most cases I have found it will join after a few attempts. Using the `/rageshake` command in Element is helpful for us to track it down, because it gives us useful logs. Please link to this issue when doing so if you can.

Unfortunately while we can reproduce the intermittent failure, the continuous failures could be a few things. Again, unfortunately mass testing is the only way you'll find some of these bugs.

**Comment by NineBAR** [comment]
Yeah -- I'm running into this exact issue. I administer my own homeserver. I've looked high and low for documentation about the necessary parameters for the room, and tried just about all variations of access. Sometimes it'll tell me I can't add a user (though it does successfully make @feeds:integrations.ems.host a moderator). Sometimes it just fails without explanation.

**Comment by NineBAR** [comment]
> Yeah -- I'm running into this exact issue. I administer my own homeserver. I've looked high and low for documentation about the necessary parameters for the room, and tried just about all variations of access. Sometimes it'll tell me I can't add a user (though it does successfully make @feeds:integrations.ems.host a moderator). Sometimes it just fails without explanation.

Magically fixed in the element update that rolled out today.

**Comment by natrius** [comment]
From my side this is solved as the last times i added the feed-bot it worked like at charm! :)

**Comment by boozook** [comment]
I've just got it. Needed settings without Moderator PL remapping:

```jsonc
notifications.room: 20
state_default: 20 // why so?!
content.events."uk.half-shot.matrix-hookshot.feed": 20
unsigned.events."uk.half-shot.matrix-hookshot.feed": 20
unsigned.users."@feeds:integrations.ems.host": 20
```
