### ISSUE TITLE
Possibility to name custom widgets to represent their content …

### ISSUE THREAD

**Issue by fooness** [element-hq/element-integration-manager#69]
I wonder if there’s any plans to add a `rename` option to custom widgets added via either scalar or the `/addwidget` command. Currently, all custom widgets are simply titled “Custom Widget” and as of now this cannot be changed as far as I know?

_Tried search for “title custom widget” and “name custom widget” and did not find anything, sorry if this is a duplicate even though …_

**Comment by Half-Shot** [comment]
You can set the names of widgets in the new UI:

![image](https://user-images.githubusercontent.com/2072976/229775358-1ec2f646-3add-4c1d-b3c1-e92a5df0420b.png)

![image](https://user-images.githubusercontent.com/2072976/229775413-6861d657-f119-47b2-9c7d-de52f1957fd9.png)

Setting a custom avatar / widget "type" is not supported however.
